# ~/.bash_logout: executed by bash(1) when login shell exits.

# when leaving the console clear the screen to increase privacy

if [ "$SHLVL" = 1 ]; then                                                   # Check if your Shell Level is 1. which is the root shell level
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q              # If so, then clear the console if possible to increase privacy when logging out.
fi
