platform='unknown'
unamestr=`uname`

if [[ "$unamestr" == 'Linux' ]]; then
    platform='LINUX'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
    platform='BSD'
elif [[ "$unamestr" == 'Darwin' ]]; then
    platform='OSX'
fi


test -f ~/.bashrc && source ~/.bashrc
test -f ~/.profile && source ~/.profile
test -f ~/.inputrc && source ~/.inputrc

test -f ~/.bash_"$platform" && source ~/.bash_"$platform"


# Set architecture flag
export ARCHFLAGS="-arch x86_64"
# Ensure user-installed binaries take precidence
export PATH=/usr/local/bin:$PATH


# The next line enables bash completion.
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/donjuma/Downloads/google-cloud-sdk/path.bash.inc ]; then
  source '/Users/donjuma/Downloads/google-cloud-sdk/path.bash.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/donjuma/Downloads/google-cloud-sdk/completion.bash.inc ]; then
  source '/Users/donjuma/Downloads/google-cloud-sdk/completion.bash.inc'
fi

# The next line will import sensitive rc files that are not in repo
if [ -f ~/.bash_secrets ]; then
    source ~/.bash_secrets
fi

export ANDROID_HOME=/Users/$USER/Library/Android/sdk
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
